---
title: "Big_data_Science"
author: "UMWIZA_Odile"
date: "2025-10-16"
output: html_document
---
```{r}
data("women")
fit<-lm(weight~height, data=women)
summary(fit)
```
```{r}
women$weight
```
```{r}
fitted(fit)
```

```{r}
residuals(fit)
```

```{r}
plot(women$height,women$weight,xlab="Height (in inches)",ylab="Weight
(in pounds)")
abline(fit)
```
```{r}
fit2<- lm(weight~height+I(height^2), data=women)
summary(fit2)
```
```{r}
plot(women$height,women$weight,xlab="Height (in inches)",ylab="Weight
(in pounds)")
lines(women$height,fitted(fit2))
```

```{r}
fit<- lm(weight~height,data=women)
par(mfrow=c(2,2))
plot(fit)
```
```{r}
fit2<- lm(weight~height+I(height^2), data=women)
par(mfrow=c(2,2))
plot(fit2)
```
```{r}
newfit<-lm(weight~height+I(height^2),data=women[-c(13,15),])
par(mfrow=c(2,2))
plot(newfit)
```
```{r}
plot(mpg~wt,data=mtcars)
model<- lm(mpg~wt, data=mtcars)
#plot(model)
abline(model)
```
```{r}
summary(model)
```

```{r}
predict(model,newdata=data.frame(wt=6))
```

```{r}
x <- rnorm(10)
pnorm(2)
```

```{r}
x <- rnorm(10, 20, 2)

```

```{r}
set.seed(1)
rnorm(5)
```
```{r}
set.seed(1)
```


```{r}
set.seed(20)
```

```{r}
x <- rnorm(100)
```
```{r}
e <- rnorm(100, 0, 2)
```

```{r}
y <- 0.5 - 2 * x + e
plot(x, y)
```


```{r}
set.seed(1)
sample(1:10, 4)
```

```{r}
sample(1:10, 4)
```

```{r}
sample(letters, 5)
```
```{r}
sample(1:10)
```

```{r}
sample(1:10)
```
```{r}
sample(1:10, replace = TRUE)
```
```{r}
# Define vectors
country <- c("Australia", "Austria", "Belgium", "Canada",
             "Denmark", "Finland", "France", "Germany",
             "Greece", "Ireland", "Italy", "Japan", "Netherland",
             "New Zealand", "Norway", "Portugal", "Spain", "Sweden",
             "Switzerland", "UK", "USA")

Income.inequality <- c(7.0, 4.8, 4.6, 5.6, 4.3, 3.7, 5.6, 5.2, 6.2, 6.0, 
                       6.7, 3.4, 5.3, 6.8, 3.9, 8.0, 5.5, 4.0, 5.7, 7.2, 8.6)

Index.HS <- c(0.07, 0.01, -0.23, -0.07, -0.19, -0.43, 0.05, -0.06, 0.38, 0.25, 
              -0.12, -1.26, -0.51, 0.29, -0.63, 1.18, -0.30, -0.83, -0.46, 0.79, 2.02)

GDP_WB <- c(45926, 47682, 43435, 45066, 45537, 30676, 39328, 46401, 26851, 49393, 
            35463, 36319, 48253, 37679, 65615, 28760, 33629, 45297, 59540, 40233, 54630)

# Create data frame
data.21 <- data.frame(country, Income.inequality, Index.HS, GDP_WB)

# Scatter plot of Income Inequality vs HS Index
plot(data.21[c("Income.inequality", "Index.HS")],
     main = "Income Inequality vs HS Index",
     xlab = "Income Inequality",
     ylab = "HS Index",
     pch = 19, col = "blue")

```
```{r}
Index_inequality.df<-data.21[c("Income.inequality","Index.HS")]
str(Index_inequality.df)
```


```{r}
(country<-data.21[,"country"])
```

```{r}
(country.2<-data.21["country"])
```


```{r}
str(country)
```
```{r}
str(country.2)
```
```{r}
plot(Index_inequality.df,pch=20)
text(Index_inequality.df,labels=country)
```



```{r}
plot(Index_inequality.df,pch=20)
text(Index_inequality.df,labels=country,pos=1)
```

```{r}
plot(Index_inequality.df,pch=20)
text(Index_inequality.df,labels=country,pos=2)
```
```{r}
plot(Index_inequality.df,pch=20)
text(Index_inequality.df,labels=country,pos=3)
```

```{r}
plot(Index_inequality.df,pch=20)
text(Index_inequality.df,labels=country,pos=4)
```
```{r}
plot(Index_inequality.df,pch=20)
text(Index_inequality.df,labels=country,pos=4,cex=0.8)
```
```{r}
which(country %in% c("Austria","Denmark","Germany","Netherland"))
```
```{r}
text.left<-which(country %in% c("Austria","Denmark","Germany","Netherla
nd"))
text.left
```

```{r}
text.right<-setdiff(1:nrow(data.21),text.left)
text.right
```

```{r}
pos.text<-ifelse(1:nrow(data.21)%in% text.left,2,4)
plot(Index_inequality.df,pch=20,col="red",xlim=c(3,9),ylim=c(-1.5,2.5))
text(Index_inequality.df,labels=country,pos=pos.text,cex=0.8)
```
```{r}
which(country %in% "Germany")
```

```{r}
text.up<-which(country %in% "Germany")
text.up
```
```{r}
text.left<-setdiff(1:nrow(data.21),c(text.right,text.up))
text.left
```

```{r}

text.up <- c(1, 3, 5)    
text.left <- c(2, 4, 6)  


pos.text <- ifelse(1:nrow(data.21) %in% text.up, 3, 
                   ifelse(1:nrow(data.21) %in% text.left, 2, 4))


plot(data.21$Income.inequality, data.21$Index.HS,
     pch = 20, col = "red",
     xlim = c(3, 9), ylim = c(-1.5, 2.5),
     xlab = "", ylab = "", main = "")

text(x = data.21$Income.inequality, 
     y = data.21$Index.HS, 
     labels = data.21$country, 
     pos = pos.text, cex = 0.8)


title(main = "Income inequality vs Index of Health and Social problems",
      xlab = "Income inequality (5th Ratio)",
      ylab = "Index of Health and Social problems")

```

```{r}
plot(Index_inequality.df,pch=20,col="red",xlim=c(3,9),ylim=c(-1.5,2.5),
ann=FALSE)
text(Index_inequality.df,labels = country,pos=pos.text,cex=0.8)
main.title<-"Income inequality vs Index of Health and Social problems"
x.lab<-"Income inequality (5th Ratio)"
y.lab<-"Index of Health and Social problems"
title(main=main.title,xlab=x.lab,ylab=y.lab)
mtext(c("Better","Worse"),side=2,at=c(-1.8,2.8),las=1)
```
```{r}

plot(Index_inequality.df, pch=20, col="red", xlim=c(3,9), ylim=c(-1.5,2.5), ann=FALSE)

text(Index_inequality.df, labels=country, pos=pos.text, cex=0.8)

main.title <- "Income inequality vs Index of Health and Social problems"
x.lab <- "Income inequality (5th Ratio)"
y.lab <- "Index of Health and Social problems"
title(main=main.title, xlab=x.lab, ylab=y.lab)

mtext(c("Better","Worse"), side=2, at=c(-1.8,2.8), las=1)

r_value <- round(cor(Index_inequality.df[[1]], Index_inequality.df[[2]]), 2)
text(x=5, y=1.5, labels=paste("r =", r_value))

```
```{r}

plot(Index_inequality.df, pch=20, col="red", xlim=c(3,9), ylim=c(-1.5,2.5), ann=FALSE)

text(Index_inequality.df, labels=country, pos=pos.text, cex=0.8)

main.title <- "Income inequality vs Index of Health and Social problems"
x.lab <- "Income inequality (5th Ratio)"
y.lab <- "Index of Health and Social problems"
title(main=main.title, xlab=x.lab, ylab=y.lab)

mtext(c("Better","Worse"), side=2, at=c(-1.8,2.8), las=1)


r_value <- round(cor(Index_inequality.df[[1]], Index_inequality.df[[2]]), 2)
text(x=5, y=1.5, labels=paste("r =", r_value))


lm.ineq <- lm(Index.HS ~ Income.inequality, data=Index_inequality.df)
abline(lm.ineq, col="blue")

```
```{r}
rm(list=ls(all=TRUE))
###set.seed(1002)
n <-30 ## number of observations
M <- 1 ## number of pathways
p<-5
z <- matrix(runif(n * p, 0, 1), nrow=n, ncol=p)
x <- 3*cos(z[, 1]) + 2*rnorm(n)
x<-as.matrix(x)
beta.true <- rep(1,ncol(x))
## pathway-response function
hfun1 <- function(zvec) (10*cos(zvec[1]) - 15*(zvec[2])^2+10*exp(-zvec
[3])*zvec[4]-8*sin(zvec[5])*cos(zvec[3])+20*(zvec[1]*zvec[5]))
h1 <- apply(z, 1, hfun1) ## only depends on z1,z2,z3,z4,z5
eps <- rnorm(n)
y <-x * beta.true + h1+ eps
```

