---
title: "Big_data_Science"
author: "UMWIZA_Odile"
date: "2025-10-16"
output: html_document
---
```{r}
f<-function(x) x^2
formals(f)
```

```{r}
body(f)
```
```{r}
environment(f)
```
```{r}
pvalues<-c(.867,0.0054,0.0018,0.1572,0.0183,0.5386)
results<-ifelse(pvalues<0.05,"Significant"," Not significant")
results
```
```{r}
x<-runif(1,0,10)
if(x>3){
y<-10
}else {
y<-0
}
```

```{r}
y<-if (x>3){
10
}else {
0
}
```

```{r}
for(i in 1:10){
print(i)}
```
```{r}
x<-c("a","b","c","d")
```

```{r}
x[3]
```

```{r}
for(i in 1:5){
print(x[i])
}
```

```{r}
for(i in 1:5)print(1:i)
```

```{r}
for(i in 5:1)print(1:i)
```

```{r}
count<-1
while (count<10){
print(count)
count<-count+1
}
```
```{r}
z<-5
set.seed(1)
while(z>= 3 && z<=10){
coin<-rbinom(1,1,0.5)
if (coin==1){
z=z+1
} else {
z<-z-1
}
}
print(z)
```

```{r}
for (i in 1:100){
print(1:i)
if (i>20){
break
}
}
```
```{r}
f1 <- function(x) {
  result <- x^2 + 2
  return(result)
}

f2 <- function(x, y) {
  result <- x^2 + y^2 - 4
  return(result)
}

f <- function(x, y) {
  result <- x + (2 * y) + 3
  return(result)
}

```

```{r}
f(2,3)
```

```{r}
a<-4
sqrt(4)
## [1] 2
b<- c(1,243,5.754,2.987)
round(b)
```

```{r}
c<-matrix(runif(12),nrow=3)
c
```

```{r}
log(c)
```

```{r}
mean(c)
```

```{r}
fix_missing<-function(x){
x[x==-99]<-NA
x
}
function1<-function(x){
x^2
}
curve(function1,-4,4)
```
```{r}
str(Titanic)
```

```{r}
View(Titanic)
apply(Titanic,c(1,2),sum )
```
```{r}
options(digits = 2)
apply(Titanic,c(1,2),sum)[3:4,]
```

```{r}
apply(Titanic,c(1,4),sum)[3:4,]
```

```{r}
apply(Titanic,c(1,2,4),sum)
```

```{r}
apply(Titanic,c(1,2,4),sum)[3:4,,]
```
```{r}
ftable(apply(Titanic,c(1,4,2),sum)[3:4,,])
```

```{r}
ftable(apply(Titanic,c(1,4,2),sum)[3:4,,])[1:2,]
```

```{r}
ftable(apply(Titanic,c(1,4,2),sum)[3:4,,])[3:4,]
```

```{r}
digit=2
prop.table(ftable(apply(Titanic,c(1,4,2),sum)[3:4,,])[1:2,], margin = 2)
```

```{r}
prop.table(ftable(apply(Titanic,c(1,4,2),sum)[3:4,,])[3:4,], margin = 2)
```
```{r}

tab <- apply(Titanic, c(1, 4, 2), sum)   
tab_sub <- tab[3:4, , ]                   
ftab <- ftable(tab_sub)[1:2, ]           
prop_tab <- prop.table(ftab, margin = 2) 

result <- matrix(prop_tab, nrow = 2,
                 dimnames = list(dimnames(Titanic)$Survived,
                                 dimnames(Titanic)$Sex))

result

```
```{r}

tab <- apply(Titanic, c(1, 4, 2), sum)

tab_sub <- tab[3:4, , ]
ftab <- ftable(tab_sub)[3:4, ]

prop_tab <- prop.table(ftab, margin = 2)
result <- matrix(prop_tab, nrow = 2,
                 dimnames = list(dimnames(Titanic)$Survived,
                                 dimnames(Titanic)$Sex))

result

```
```{r}
Student <- c("John ncuti", "Angela bakame", "Bruce wizeye", "Alexis aganze", 
             "claude Rukundo", "Joel Kagabo", "Mary ineza")
Math <- c(600, 412, 358, 495, 512, 410, 522)
Science <- c(95, 99, 80, 82, 75, 89, 77)
English <- c(25, 22, 18, 20, 29, 30, 27)

roster <- data.frame(Student, Math, Science, English, stringsAsFactors = FALSE)

str(roster)

```
```{r}
z<-scale(roster[,2:4])
```

```{r}
score<-apply(z,1,mean)
roster<-cbind(roster,score)
```

```{r}
y<-quantile(score,c(.8,.6,.4,.2))
```

```{r}
## create a grade variable us
roster$grade[score>=y[1]]<-"A"
roster$grade[score<y[1]&score>=y[2]]<-"B"
roster$grade[score<y[2]& score>=y[3]]<-"C"
roster$grade[score<y[3]& score>=y[4]]<-"D"
roster$grade[score<y[4]]<-"F"
```

```{r}
#### Dealing with names
name<-strsplit((roster$Student),"")
lastname<-sapply (name,"[",2)
firstname<-sapply(name,"[",1)
roster<-cbind(firstname, lastname,roster[,-1])
roster<-roster[order(lastname,firstname),]
roster
```

```{r}
cars<-mtcars[1:5, 1:4]
cars
```

```{r}
t(cars)
```

```{r}
options(digits=3)
attach(mtcars)
aggdata<-aggregate(mtcars,by=list(cyl,gear),FUN=mean,na.rm=TRUE)
```
```{r}
id<-c(1,1,2,2)
time<-c(1,2,1,2)
x1<-c(5,3,6,2)
x2<-c(6,5,1,4)
mydata<-data.frame(id,time,x1,x2)
```

```{r}

```

