---
title: "Big_data_Science"
author: "UMWIZA_Odile"
date: "2025-10-16"
output: html_document
---


```{r}
data1 <- read.table(text="
Sept_2022 Oct_2022 Nov_2022 Dec_2022 Jan_2023 Feb_2023 Mar_2023 Apr_2023 May_2023 June_2023
1 4 6 30 140 67 47 23 39 134 80
2 10 2 29 164 72 81 28 63 211 132
", header=TRUE)

barplot(as.matrix(data1), main="Confirmed cases Vs Gender", beside=TRUE,
        col=c("gold3","red"))
legend("topright", c("Male","Female"), cex=0.5, bty="n", fill=c("gold3","red"))

```
```{r}
data3 <- read.table(text="
sept_2022 Oct_2022 Nov_2022 Dec_2022 Jan_2023 Feb_2023 Mar_2023 Apr_2023 May_2023 June_2023
1 867 582 1802 12003 3059 9205 5346 7269 5933 324
2 842 436 1805 11785 3508 10908 4902 7883 5901 464
", header=TRUE)

barplot(as.matrix(data3), main="COVID-19 test Vs Gender", beside=TRUE,
        col=c("blue","purple"))
legend("topleft", c("Male","Female"), cex=1.3, bty="n", fill=c("blue","purple"))

```
```{r}
data2 <- read.table(text="
Sept_2022 Oct_2022 Nov_2022 Dec_2022 Jan_2023 Feb_2023 Mar_2023 Apr_2023 May_2023 June_2023
1 0 0 1 9 8 7 1 4 11 22
2 11 3 41 242 104 78 44 86 244 147
3 3 5 17 53 27 43 6 12 90 43
", header=TRUE)

barplot(as.matrix(data2), main="Confirmed cases Vs Age categories", beside=TRUE,
        col=c("green","blue","purple"))

legend("topleft", 
       c("Less than 15 years","15-49 years","Above 50"), 
       cex=1.3, bty="n", fill=c("green","blue","purple"))

```
```{r}
months<-c("Sept_2022","Oct_2022","Nov_2022","Dec_2022", "Jan_2023","Feb
_2023","Mar_2023","Apr_2023","May_2023","June_2023")
Confirmed_covid<-c(14,8,59,304,139,128,51,102,345,212)
plot(Confirmed_covid, type = "l",pch=21, col = "red",ylim=c(0,350),
xaxt="n", ylab = "Number of patients ",
main = "Confirmed cases Vs treatment ")
treatment<- c(12,0,26,217,104,57,12,47,23,20)
lines(treatment, col="blue",lty=2)
legend("topleft", legend=c("Received treatment", "Confirmed"),cex=0.5,
fill = c("blue","red"))
axis(1,at=1:10,lab=c("Sept_2022","Oct_2022","Nov_2022","Dec_2022", "Jan
_2023","Feb_2023","Mar_2023","Apr_2023","May_2023","June_2023"))
```
```{r}
months<-c("sept_2022","Oct_2022","Nov_2022","Dec_2022", "Jan_2023","feb
_2023","Mar_2023","Apr_2023","May_2023", "June_2023")
number_of_test<-c(1709, 1018, 3607,23788,6567,20113,10248,15152,11834,
7891)
plot(number_of_test, type = "o", col = "blue",ylim=c(0,24000),
xaxt="n", ylab = "Number of Test",
main = "COVID 19 Test")
axis(1,at=1:10,lab=c("Sept_2022","Oct_2022","Nov_2022","Dec_2022", "Jan
_2023","Feb_2023","Mar_2023","Apr_2023","May_2023","June_2023"))
```
```{r}
data(mtcars)
```

```{r}
table(mtcars$cyl)
```

```{r}
barplot(table(mtcars$cyl),
        main="Distribution of car Cylinder counts",
        xlab="Number of cylinders",
        ylab="Number of cars")

```
```{r}
barplot(table(mtcars$cyl),
        main="Distribution of car Cylinder counts",
        xlab="Number of cylinders",
        ylab="Number of cars",
        horiz=TRUE)

```
```{r}
plot(mtcars$mpg~mtcars$wt,main="Automobile Data",xlab="Weight",ylab=" M
iles per Gallon")
```
```{r}
plot(mtcars$mpg ~ mtcars$wt,
     main="Automobile Data",
     xlab="Weight",
     ylab="Miles per Gallon")

plot(mtcars$mpg ~ mtcars$wt,
     pch=17,
     main="Automobile Data",
     xlab="Weight",
     ylab="Miles per Gallon")

```
```{r}
plot(mtcars$mpg ~ mtcars$wt,
     pch=21,
     main="Automobile Data",
     xlab="Weight",
     ylab="Miles per Gallon")

```
```{r}
plot(mtcars$mpg ~ mtcars$wt,
     type="l",     # line plot
     lty=2,        # dashed line
     lwd=2,        # line width
     col="red",
     main="Automobile Data",
     xlab="Weight",
     ylab="Miles per Gallon")

```
```{r}
library(ggplot2)
ggplot(data=mtcars, aes(x=wt,y=mpg))+geom_point()+
labs(title = "Automobile Data",x="Weight",y="Miles per Galon")
```
```{r}
library(ggplot2)

ggplot(data = mtcars, aes(x = wt, y = mpg)) +
  geom_point(pch = 17, color = "blue", size = 1) +
  geom_smooth(method = "lm", color = "green") +
  labs(title = "Automobile Data",
       x = "Weight",
       y = "Miles per Gallon")

```
```{r}
library(ggplot2)

f0 <- ggplot(data = mtcars, aes(x = wt, y = mpg)) +
  geom_point(shape = 24, fill = 1, size = 3) +  # increased size for visibility
  geom_smooth(method = "lm", color = "blue")

f0

```
```{r}
f1<-f0+theme_bw()
f1
```

```{r}
f2<-f1+
theme(panel.grid = element_line(linetype = "dotted",color = "Black"))
f2
```
```{r}
data(mtcars)
mtcars$am<-factor(mtcars$am, levels =c(0,1),
labels= c("Automatic","Manual"))
mtcars$vs<-factor(mtcars$vs, levels =c(0,1),
labels=c("V-Engine","Straight Engine"))
mtcars$cyl<-factor(mtcars$cyl)
ggplot(data=mtcars,aes(x=hp,y=mpg,shape=cyl,color=cyl))+
geom_point(size=3)+
facet_grid(vs~am)+
labs(title = "Automobile Data by Engine Type",x="HorsePower",y="Miles
per Gallon")
```

```{r}
data(singer,package="lattice")
ggplot(singer,aes(x=voice.part,y=height))+geom_boxplot()
```
```{r}
data2<- data.frame(x=1:3, y=c("a","b","c"))
str(data2)
```

```{r}
(cbind(data2,data.frame(z=3:1)))
```

```{r}
(rbind(data2,data.frame(x=10,y="z")))
```

```{r}
women
```

```{r}
head(women)
```
```{r}
summary(women)
```
```{r}
manager <- c(1,2,3,4,5)
country <- c("US","US","UK","UK","UK")
gender <- c("M","F","F","M","F")
age <- c(32,45,25,39,99)
q1 <- c(5,3,3,3,2)
q2 <- c(4,5,5,3,2)
q3 <- c(5,2,5,4,1)
q4 <- c(5,5,5,NA,2)
q5 <- c(5,5,2,NA,1)
leadership <- data.frame(manager, country, gender, age, q1, q2, q3, q4, q5,
                         stringsAsFactors = FALSE)
str(leadership)

```

```{r}
names(leadership)
```

```{r}
leadership$age[leadership$age==99]<-NA
leadership$agecat[leadership$age >75]<-"Elder"
leadership$agecat[leadership$age>=35 & leadership$age<=75]<-"Middle Age
d"
leadership$agecat[leadership$age <35]<- "Young"
```

```{r}
is.na(leadership[,5:9])
```

```{r}
newdata<-na.omit(leadership)
newdata
```

```{r}
order(leadership$age)
```

```{r}
newdata2<-leadership[order(leadership$age),]
```


```{r}
newdata3<-leadership[,c(5:9)]
myvars<-c("q1","q2","q3","q4","q5")
newdata3<-leadership[myvars]
newdata4<-leadership[,c(-1,-2)]
newdata4<-leadership[,-(1:5)]
newdata5<-leadership[,c(-1,-7)]
leadership[[4]]
```

```{r}
leadership$age
```

```{r}
newdata6<-leadership[c(-1,-3),]
newdata6<-leadership[c(2,4,5),]
newdata7<-subset(leadership,age>=35|age<24,select=c(q1,q2,q3,q4,q5))
attach(leadership)
```

```{r}
#newdata7<-leadership[gender="M" & age>30,]
newdata7<-leadership[gender=="M" & age>30,]
detach(leadership)
```

```{r}
install.packages("nycflights13")
library(nycflights13)
```
```{r}
library(dplyr)
```

```{r}
str(flights)
```
```{r}
jan<-filter(flights,month==1)
jan
```
```{r}
newyear<-filter(flights,month==1, day==1)
newyear
```

```{r}
dec25<-filter(flights,month==12, day==25)
dec25
```

```{r}
jan_dec<-filter(flights,month==1|month==12)
jan_dec
```
```{r}
nov_dec<-filter(flights,month %in% c(11,12))
```

```{r}
data_10<-arrange(flights,year,month,day)
arrange(flights,desc(arr_delay))
```

```{r}
time_var<-select(flights, year,month, day)
select(flights, year:day)
```
```{r}
select(flights,-(year:day))
```
```{r}
flights2<-select(flights,year:day,ends_with("delay"),distance,air_time)
(mutate(flights2,gain=arr_delay-dep_delay,
speed=distance/air_time*60))
```
```{r}

```

